# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CoordinateCapture
                                 A QGIS plugin
 Python port of the deprecated Coordinate Capture core plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-07-04
        copyright            : (C) 2020 by Stefanos Natsis
        email                : uclaros@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CoordinateCapture class from file CoordinateCapture.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .coordinate_capture import CoordinateCapture
    return CoordinateCapture(iface)
